version: "3"
services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: php
    restart: always
    volumes:
      - ./src:/var/app
      - /var/app/vendor
    networks:
      - app-network
    ports:
      - "3000:80"
    environment:
      - LARAVEL_ENV=dev

networks:
  app-network:
    driver: bridge
